AdministrationApp/urls.py
from django.contrib import admin
from django.urls import path
from AdministrationApp.views import ErrorSubmit, DashboardView
from AdministrationApp.views import PatentRegistrationView, PatentTableView, PatentEditView, PatentDeleteView
from AdministrationApp.views import QuickAppointmentTableView, QuickAppointmentEditView, QuickAppointmentDeleteView
from AdministrationApp.views import AppointmentTableView, AppointmentEditView, AppointmentDeleteView
from AdministrationApp.views import TodayTableView, TomorrowTableView
from AdministrationApp.views import NurseRegisterView, DeleteNurseView
from AdministrationApp.views import AdministrationLoginView
from AdministrationApp.views import AddGalleryImage, DeleteGalleryImage
from AdministrationApp.views import AddFeedbackView, DeleteFeedbackView
from AdministrationApp.views import AddDoctorsProfileView, DeleteDoctorsProfileView
from AdministrationApp.views import ShopRequestTableView, ShopRequestStatusChangeView, DeleteShopRequestView
from AdministrationApp.views import MessageTableView, DeleteMessageView
from AdministrationApp.views import SubscribersTableView, DeleteSubscribersView
from AdministrationApp.views import AddShopItemView, DeleteShopItemView
from AdministrationApp.views import SearchPatientTableView
from AdministrationApp.views import SearchAppointmentTableView
from AdministrationApp.views import SearchQuickAppointmentTableView
from AdministrationApp.views import AddCountView, DeleteCountView
from AdministrationApp.views import AddGoogleMeetView, DeleteGoogleMeetView
from AdministrationApp.views import AddTodoView, EditTodoView, EditTodoStatusView, DeleteTodoView
from AdministrationApp.views import AddNotesView, DeleteNotesView
from AdministrationApp.views import AddAccountView, file_load_view, DeleteAccountView, DeleteAllAccountWarnningView, DeleteAllAccountView
from AdministrationApp.views import AddSocialMediaView, DeleteSocialMediaView

urlpatterns = [
    path('login/', AdministrationLoginView, name='administration_login'),
    path('error/',ErrorSubmit, name='error_submit'),
    path('', DashboardView, name='administration_home'),
    
    path('patent_registration/', PatentRegistrationView, name='patent_registration'),
    path('patents/', PatentTableView, name='patent_table'),
    path('patent/<int:id>/edit/', PatentEditView, name='patent_edit'),
    path('patent/<int:id>/delete/', PatentDeleteView, name='patent_delete'),

    path('quick_appointment/', QuickAppointmentTableView, name='quick_appointment_table'),
    path('quick_appointment/<int:id>/edit/', QuickAppointmentEditView, name='quick_appointment_edit'),
    path('quick_appointment/<int:id>/delete/', QuickAppointmentDeleteView, name='quick_appointment_delete'),

    path('appointment/', AppointmentTableView, name='appointment_table'),
    path('appointment/<int:id>/edit/', AppointmentEditView, name='appointment_edit'),
    path('appointment/<int:id>/delete/', AppointmentDeleteView, name='appointment_delete'),

    path('shop_request/', ShopRequestTableView, name='shop_request'),
    path('update_shop_request/<int:id>', ShopRequestStatusChangeView, name='update_shop_request'),
    path('shop_request/<int:id>/delete', DeleteShopRequestView, name='delete_shop_request'),
    
    path('message/', MessageTableView, name='message_table'),
    path('message/<int:id>/delete', DeleteMessageView, name='delete_message'),

    path('subscribers/', SubscribersTableView, name='subscribers_table'),
    path('subscribers/<int:id>/delete', DeleteSubscribersView, name='delete_subscribers'),

    path('today/', TodayTableView, name='today'),
    path('tomorrow/', TomorrowTableView, name='tomorrow'),

    # path('nurse/', NurseRegisterView, name='nurse_register'),
    path('register/', NurseRegisterView.as_view(), name="nurse_register"),
    path('delete/<int:id>', DeleteNurseView, name="delete_nurse"),


    path('add_image/', AddGalleryImage.as_view(), name="add_gallery_image"),
    path('image/<int:id>/delete/', DeleteGalleryImage, name="image_delete"),
    
    path('add_feedback/', AddFeedbackView.as_view(), name="add_feedback"),
    path('feedback/<int:id>', DeleteFeedbackView, name="delete_feedback"),

    path('doctors_profile/', AddDoctorsProfileView.as_view(), name="add_doctors_profile"),
    path('doctors_profile/<int:id>/delete/', DeleteDoctorsProfileView, name="delete_doctors_profile"),

    path('add_shop/', AddShopItemView.as_view(), name="add_shop_item"),
    path('shop/<int:id>/delete', DeleteShopItemView, name="delete_shop_item"),
    
    path('search_patient', SearchPatientTableView, name="search_patient_table"),
    path('search_appointment', SearchAppointmentTableView, name="search_appointment_table"),
    path('search_quick_appointment', SearchQuickAppointmentTableView, name="search_quick_appointment_table"),
    
    path('add_count', AddCountView, name="add_count"),
    path('add_count/<int:id>/delete', DeleteCountView, name="delete_count"),
    
    path('add_google-meet', AddGoogleMeetView, name="add_google_meet"),
    path('add_google-meet/<int:id>/delete', DeleteGoogleMeetView, name="delete_google_meet"),
    
    path('add_todo', AddTodoView, name="add_todo"),
    path('edit_todo/<int:id>', EditTodoView, name="edit_todo"),
    path('todo_status_change/<int:id>', EditTodoStatusView, name="todo_status_change"),
    path('todo_delete/<int:id>/delete', DeleteTodoView, name="todo_delete"),
    
    path('add_notes', AddNotesView, name="add_notes"),
    path('delete_notes/<int:id>/delete', DeleteNotesView, name="delete_notes"),
    
    path('add_account', AddAccountView, name="add_account"),
    path('export/csv/$', file_load_view, name="export_data"),
    path('delete_account/<int:id>', DeleteAccountView, name="delete_account"),
    path('delete_all_account_warnning', DeleteAllAccountWarnningView, name="delete_all_account_warnning"),
    path('delete_all_account', DeleteAllAccountView, name="delete_all_account"),
    
    path('add_social_media', AddSocialMediaView, name="add_social_media"),
    path('delete_social_media<int:id>', DeleteSocialMediaView, name="delete_social_media"),
]

HomeApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView, name='home'),
    path('about/', views.AboutView, name='about'),
    path('services/', views.ServicesView, name='services'),
    path('gallery/', views.GalleryView, name='gallery'),
    path('shop/', views.ShopView, name='shop'),
    path('shop/<int:id>', views.ShopDetailView, name='shop_detail'),
    
    path('contact/', views.ContactView, name='contact'),
    path('appointment/', views.AppointmentView, name='appointment'),

    path('migraine/', views.MigraineView, name='migraine'),
    
    path('musculoskeletal/', views.MusculoskeletalView, name='musculoskeletal'),
    path('musculoskeletal/elbow', views.ElbowView, name='elbow'),
    path('musculoskeletal/hip', views.HipView, name='hip'),
    path('musculoskeletal/ankle', views.AnkleView, name='ankle'),
    path('musculoskeletal/shoulder', views.ShoulderView, name='shoulder'),
    path('musculoskeletal/wrist', views.WristView, name='wrist'),
    path('musculoskeletal/knee_joint', views.KneeJointView, name='knee_joint'),
    path('musculoskeletal/head_neck', views.HeadNeckView, name='head_neck'),
    path('musculoskeletal/lumbar_spine', views.LumbarSpineView, name='lumbar_spine'),

    path('neurology/', views.NeurologyView, name='neurology'),
    path('neurology/neurology_note', views.NeurologyNoteView, name='neurology_note'),
    
    path('pediatrics/', views.PediatricsView, name='pediatrics'),
    path('paediatric/paediatric_note', views.PaediatricNoteView, name='paediatric_note'),
    path('paediatric/monthly_baby_milestone', views.MonthlyBabyMilestoneView, name='monthly_baby_milestone'),

    path('success/', views.SuccessView, name='success'),
    path('error/', views.ErrorView, name='error'),
    path('search_products/', views.SearchProductsView, name="search_products"),
]

MyProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HomeApp.urls')),
    path('administration/', include('AdministrationApp.urls')),
    path('blog/', include('TheBlog.urls')),

    path('login/', include('django.contrib.auth.urls')),
    path('login/', include('LoginApp.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

AdministrationApp/models.py
from django.db import models

class PatentRegistration(models.Model):
    name = models.CharField(max_length=400, null=True, blank=True)
    age = models.CharField(max_length=400, null=True, blank=True)
    remark = models.CharField(max_length=1000, null=True, blank=True)
    place = models.CharField(max_length=400, null=True, blank=True)
    mobile = models.CharField(max_length=400, null=True, blank=True)
    other_contact = models.CharField(max_length=400, null=True, blank=True)
    booking_date = models.DateField(null=True, blank=True)
    submit_date = models.DateField(null=True, blank=True)
    flag = models.BooleanField(default=False,null=True,blank=True)

    def __str__(self):
        return self.name


class QuickAppointment(models.Model):
    name = models.CharField(max_length=400, null=True, blank=True)
    age = models.CharField(max_length=400, null=True, blank=True)
    remark = models.CharField(max_length=1000, null=True, blank=True)
    place = models.CharField(max_length=400, null=True, blank=True)
    mobile = models.CharField(max_length=400, null=True, blank=True)
    other_contact = models.CharField(max_length=400, null=True, blank=True)
    booking_date = models.DateField(null=True, blank=True)
    submit_date = models.DateField(null=True, blank=True)
    flag = models.BooleanField(default=False,null=True,blank=True)

    def __str__(self):
        return self.mobile


class Appointment(models.Model):
    name = models.CharField(max_length=400, null=True, blank=True)
    age = models.CharField(max_length=400, null=True, blank=True)
    remark = models.CharField(max_length=1000, null=True, blank=True)
    place = models.CharField(max_length=400, null=True, blank=True)
    mobile = models.CharField(max_length=400, null=True, blank=True)
    other_contact = models.CharField(max_length=400, null=True, blank=True)
    booking_date = models.DateField(null=True, blank=True)
    submit_date = models.DateField(null=True, blank=True)
    flag = models.BooleanField(default=False,null=True,blank=True)

    def __str__(self):
        return self.name


class Messages(models.Model):
    name = models.CharField(max_length=400, null=True, blank=True)
    email = models.CharField(max_length=400, null=True, blank=True)
    subject = models.CharField(max_length=1000, null=True, blank=True)
    message = models.CharField(max_length=400, null=True, blank=True)
    submit_date = models.DateField(null=True, blank=True)
    flag = models.BooleanField(default=False,null=True,blank=True)

    def __str__(self):
        return self.name

class Subscribe(models.Model):
    email = models.CharField(max_length=400, null=True, blank=True)
    submit_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.email

# ===============================================

class Nurse(models.Model):
    name = models.CharField(max_length=400, null=True, blank=True)
    age = models.CharField(max_length=400, null=True, blank=True)
    place = models.CharField(max_length=400, null=True, blank=True)
    username = models.CharField(max_length=1000, null=True, blank=True)
    password = models.CharField(max_length=1000, null=True, blank=True)
    email = models.EmailField(max_length=400, null=True, blank=True)
    mobile1 = models.CharField(max_length=400, null=True, blank=True)
    remark = models.CharField(max_length=400, null=True, blank=True)
    submit_date = models.DateField(null=True, blank=True)
    is_staff = models.BooleanField(default=False,null=True,blank=True)
    is_nurse = models.BooleanField(default=False,null=True,blank=True)

    def __str__(self):
        return self.name





# =================================================

class Gallery(models.Model):
   image_title = models.CharField(max_length=255)
   image = models.ImageField(blank=True, null=True, upload_to="gallery/")
   
   def __str__(self):
      return self.image_title 

   def get_absolute_url(self):
      return reverse('gallery')


class Feedback(models.Model):
    name = models.CharField(max_length=400, null=True, blank=True)
    profile_photo = models.ImageField(blank=True, null=True, upload_to="feedback/")
    Role = models.CharField(max_length=400, null=True, blank=True)
    snippets = models.CharField(max_length=400, null=True, blank=True)

    def __str__(self):
      return self.name 


class DoctorsProfile(models.Model):
    name = models.CharField(max_length=400, null=True, blank=True)
    profile_photo = models.ImageField(blank=True, null=True, upload_to="doctors/")
    mobile = models.CharField(max_length=400, null=True, blank=True)
    email = models.EmailField(max_length=400, null=True, blank=True)
    designation = models.CharField(max_length=400, null=True, blank=True)
    snippets = models.CharField(max_length=400, null=True, blank=True)
    facebook_url = models.CharField(max_length=400, null=True, blank=True)
    instagram_url = models.CharField(max_length=400, null=True, blank=True)
    twitter_url = models.CharField(max_length=400, null=True, blank=True)
    linkedin_url = models.CharField(max_length=400, null=True, blank=True)

    def __str__(self):
      return self.name 
  
  
class Shop(models.Model):
    item = models.CharField(max_length=400, null=True, blank=True)
    item_Image = models.ImageField(upload_to='shop/', blank=False, null=False) 
    price = models.CharField(max_length=400, null=True, blank=True)
    offer_price = models.CharField(max_length=400, null=True, blank=True)
    category = models.CharField(max_length=400, null=True, blank=True)
    discription = models.CharField(max_length=1000, null=True, blank=True)
    rating = models.CharField(max_length=400, null=True, blank=True)
    submit_date = models.DateField(auto_now_add=True)

    def __str__(self):
      return self.item 
  
  
class ShopRequest(models.Model):
    name = models.CharField(max_length=400, null=True, blank=True)
    mobile = models.CharField(max_length=400, null=True, blank=True)
    product_id = models.CharField(max_length=400, null=True, blank=True)
    price = models.CharField(max_length=400, null=True, blank=True)
    offer_price = models.CharField(max_length=400, null=True, blank=True)
    shop_status = models.CharField(max_length=400, null=True, blank=True)
    request_date = models.DateField(auto_now_add=True)
    is_read = models.BooleanField(default=False,null=True,blank=True)
    is_delivered = models.BooleanField(default=False,null=True,blank=True)
    

    def __str__(self):
      return self.name 
  
  
class CounterValues(models.Model):
    docter_count = models.CharField(max_length=400, null=True, blank=True)
    department_count = models.CharField(max_length=400, null=True, blank=True)
    reserchlab_count = models.CharField(max_length=400, null=True, blank=True)
    awards_count = models.CharField(max_length=400, null=True, blank=True)
    submit_date = models.DateField(auto_now_add=True)

    def __str__(self):
      return self.docter_count


class SocialMedia(models.Model):
    twitter = models.CharField(max_length=400, null=True, blank=True)
    facebook = models.CharField(max_length=400, null=True, blank=True)
    instagram = models.CharField(max_length=400, null=True, blank=True)
    google_plus = models.CharField(max_length=400, null=True, blank=True)
    linkedin = models.CharField(max_length=400, null=True, blank=True)
    submit_date = models.DateField(auto_now_add=True)

    def __str__(self):
      return self.facebook
  
  
class GoogleMeet(models.Model):
    name = models.CharField(max_length=400, null=True, blank=True)
    link = models.CharField(max_length=400, null=True, blank=True)
    submit_date = models.DateField(auto_now_add=True)

    def __str__(self):
      return self.name

class Todo(models.Model):
    todo_name = models.CharField(max_length=400, null=True, blank=True)
    todo_dead_time = models.CharField(max_length=400, null=True, blank=True)
    todo_subject = models.CharField(max_length=400, null=True, blank=True)
    todo_body = models.CharField(max_length=400, null=True, blank=True)
    todo_status = models.CharField(max_length=400, null=True, blank=True)
    submit_date = models.DateField(auto_now_add=True)

    def __str__(self):
      return self.todo_name

class Notes(models.Model):
    note_body = models.CharField(max_length=400, null=True, blank=True)
    submit_date = models.DateField(auto_now_add=True)

    def __str__(self):
      return self.note_body
  
  
class Accounts(models.Model):
    income = models.FloatField(null=True,blank=True,default=0)
    expense = models.FloatField(null=True,blank=True,default=0)
    total_expense = models.FloatField(null=True,blank=True,default=0)
    total_income = models.FloatField(null=True,blank=True,default=0)
    description = models.CharField(max_length=1000, null=True, blank=True)
    start_Date = models.DateField(null=True,blank=True)
    end_Date = models.DateField(null=True,blank=True)    
    expense_flag = models.BooleanField(default=False,null=True,blank=True)
    income_flag = models.BooleanField(default=False,null=True,blank=True)
    
    def __str__(self):
      return self.description

AdministrationApp/templates/administration/forms/add_count.html
{% extends 'administration/admin_base.html' %}
{% load static %}

{% block title %} Ram's Rehab | Administration {% endblock title %}

{% block content %}
      
<main class="pt-5 mx-lg-5">
  <div class="container-fluid mt-5">
   {% if user.is_superuser %}
    <div class="card mb-4 wow fadeIn">
        <div class="card-body d-sm-flex justify-content-between">
          <h4 class="mb-2 mb-sm-0 pt-1">
              <span>Add Counter Values</span>
          </h4>
        </div>
    </div>

    <form action="" method="POST">
      {% csrf_token %}
    <div class="row wow fadeIn">
  
      
         <div class="col-md-6 ">
         <div class="card mb-4 ">
            <div class="card-header text-white bg-primary">Add Counter Values</div>
            <div class="card-body">
               <div class="list-group list-group-flush">
                  <div class="form-outline">
                     <label class="form-label" for="typeText1">Docters <span style="color: red;">*</span></label>
                     <input name="docter_count" value="{{ data.docter_count }}" type="text" id="typeText1" class="form-control" />
                  </div>
                  <div class="form-outline mt-2">
                     <label class="form-label" for="typeText2">Departments <span style="color: red;">*</span></label>
                     <input name="department_count" value="{{ data.department_count }}" type="text" id="typeText2" class="form-control" />
                  </div>
                  <div class="form-outline mt-2">
                     <label class="form-label" for="typeText2">Reserch Labs <span style="color: red;">*</span></label>
                     <input name="reserchlab_count" value="{{ data.reserchlab_count }}" type="text" id="typeText2" class="form-control" />
                  </div>
                  <div class="form-outline mt-2">
                     <label class="form-label" for="typeText2">Awards <span style="color: red;">*</span></label>
                     <input name="awards_count" value="{{ data.awards_count }}" type="text" id="typeText2" class="form-control" />
                  </div>
                  <div class="form-outline mt-2 d-flex justify-content-center">
                     <button type="submit" class="btn btn-sm text-white btn-primary"><b>Submit</b> </button>
                     <a href="{% url 'administration_home' %}" type="button" class="btn text-white btn-sm btn-primary"><b>Cancel</b></a>
                  </div> 
                  
               </div>
            </div>
         </div>
         </div>

         <div class="col-md-6 ">
            {% for i in data %}
            <div class="card mb-4">
               <div class="card-body">
                  <div class="list-group list-group-flush">
                     <span class="d-flex justify-content-end">
                        <a href="{% url 'delete_count' i.id %}"><span class="badge badge-danger badge-pill pull-right">Delete</span></a>
                     </span>
                     <span class="d-flex justify-content-between">
                        <span>Current Counter Values</span> 
                        <small style="padding-right: 10px;">{{ i.submit_date | date:'d / m / Y' }}</small>
                     </span> 
                     <span class="list-group-item list-group-item-action waves-effect">
                        <span class="badge badge-success badge-pill pull-right">{{ i.docter_count }}  
                        </span> &nbsp;
                        Docters
                     </span>

                     <span class="list-group-item list-group-item-action waves-effect">
                        <span class="badge badge-success badge-pill pull-right">{{ i.department_count }} 
                        </span> &nbsp;
                        Departments 
                     </span>
                     <span class="list-group-item list-group-item-action waves-effect">
                        <span class="badge badge-success badge-pill pull-right">{{ i.reserchlab_count }} 
                        </span> &nbsp;
                        Reserch Labs 
                     </span>
                     <span class="list-group-item list-group-item-action waves-effect">
                        <span class="badge badge-success badge-pill pull-right">{{ i.awards_count }} 
                        </span> &nbsp
                        Awards  
                     </span>
                  </div>
               </div>
            </div>
            {% endfor %}
            </div>
         


    </div>
   </form>
   {% else %}
   <div class="card mb-4 wow fadeIn">
      <div class="card-body text-center">
         <h4 class="mb-2 mb-sm-0 pt-1">
            <span>You are not allowed here !!</span>
         </h4>
         <h5 class="my-2 mb-sm-0 pt-1 text-danger">
            <br>
            <span>Onlu admin can change Counter values</span><br><br>
            <p>- Please Contact Admin -</p>
         </h5>
      </div>
   </div>
      {% endif %}
  </div>
</main>

{% endblock %}
      

AdministrationApp/templates/administration/forms/add_doctors_profile.html
{% extends 'administration/admin_base.html' %}
{% load static %}
{% block title %} Ram's Rehab | Administration {% endblock title %}
{% block content %}
<main class="pt-5 mx-lg-5">
   <div class="container-fluid mt-5">
      {% if user.is_superuser %}
      <div class="card mb-4 wow fadeIn">
         <div class="card-body d-sm-flex justify-content-between">
            <h4 class="mb-2 mb-sm-0 pt-1">
               <span>Add Physio Profile</span>
            </h4>
         </div>
      </div>
      <style>
         #regform.helptext{
         display:none;
         }
         #regform ul li{
         font-size:10px;
         }
      </style>
      <form action="" method="POST" enctype="multipart/form-data">
         {% csrf_token %}
         <div class="row wow fadeIn">
            <div class="col-md-9 mx-auto">
               <div class="card mb-4">
                  <div class="card-header text-white bg-primary">Add Physio Profile</div>
                  <div class="card-body">
                     <p class="text-danger text-center"> * image size : 600 x 600 pixals</p>
                     <div class="list-group list-group-flush">
                        <div id="regform" class="form-outline">
                           {{ form.media }}
                           {{ form.as_p }}
                        </div>
                     </div>
                     <div class="col-md-10 d-flex  justify-content-center mx-auto" >
                        <div class=" mb-2">
                           <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </form>
   </div>
   {% else %}
      <div class="card mb-4 wow fadeIn">
         <div class="card-body text-center">
            <h4 class="mb-2 mb-sm-0 pt-1">
               <span>You are not allowed here !!</span>
            </h4>
            <h5 class="my-2 mb-sm-0 pt-1 text-danger">
               <br>
               <span>Only admin can Add Physio Profile Details</span><br><br>
               <p>- Please Contact Admin -</p>
            </h5>
         </div>
      </div>
   {% endif %}

   {% if user.is_superuser %}
   <div class="col-md-12 mb-4 mt-4">
      <div class="card">
         <div class="card-header bg-primary text-white d-flex justify-content-between">
            <span>Physio Profile Details</span> <span>   </span>
         </div>
         <div class="card-body">
            <table class="table table-hover" >
               <thead class="blue lighten-4 text-center">
                  <tr>
                     <th>Roll</th>
                     <th>Name</th>
                     <th>Designation</th>
                     <th>Mobile</th>
                     <th>Email</th>
                     <th>Delete</th>
                  </tr>
               </thead>
               <tbody class="text-center" >
                  {% for item in data %}
                  <tr>
                     <th>{{ forloop.revcounter }}</th>
                     <th >{{ item.name |capfirst }}</th>
                     <th >{{ item.designation |capfirst }}</th>
                     <th >{{ item.mobile }}</th>
                     <th >{{ item.email }}</th>
                     <td>
                        <a class="red-text" href="{% url 'delete_doctors_profile' item.id %}"><strong><i class="fas fa-trash-alt"></i></strong></a>
                     </td>
                  </tr>
                  {% endfor %}
               </tbody>
            </table>
         </div>
      </div>
   </div>
   {% endif %}
</main>
{% endblock %}

AdministrationApp/templates/administration/forms/nurse_register_form.html
{% extends 'administration/admin_base.html' %}
{% load static %}
{% block title %} Ram's Rehab | Administration {% endblock title %}
{% block content %}
<main class="pt-5 mx-lg-5">
   <div class="container-fluid mt-5">
      {% if user.is_superuser %}
      <div class="card mb-4 wow fadeIn">
         <div class="card-body d-sm-flex justify-content-between">
            <h4 class="mb-2 mb-sm-0 pt-1">
               <span>Nurse / Staff  Registration Form</span>
            </h4>
         </div>
      </div>
      <style>
         #regform.helptext{
         display:none;
         }
         #regform ul li{
         font-size:10px;
         }
         #regform .helptext{
         font-size:10px;
         }
         #regform #id_is_staff{
         width: 30px;
         }
      </style>
      <form action="" method="POST">
         {% csrf_token %}
         <div class="row wow fadeIn">
            <div class="col-md-10 mx-auto">
               <div class="card mb-4">
                  <div class="card-header text-white bg-primary">Nurse / Staff Details</div>
                  <div class="card-body">
                     <div class="list-group list-group-flush">
                        <div id="regform" class="form-outline">
                           {{ form.as_p }}
                        </div>
                     </div>
                     <div class="col-md-10 d-flex  justify-content-center mx-auto" >
                        <div class=" mb-2">
                           <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </form>
      {% else %}
      <div class="card mb-4 wow fadeIn">
         <div class="card-body text-center">
            <h4 class="mb-2 mb-sm-0 pt-1">
               <span>You are not allowed here !!</span>
            </h4>
            <h5 class="my-2 mb-sm-0 pt-1 text-danger">
               <br>
               <span>Only admin can Add Nurse / Staff Details</span><br><br>
               <p>- Please Contact Admin -</p>
            </h5>
         </div>
      </div>
   {% endif %}

   </div>
   {% if user.is_superuser %}
   <div class="col-md-12 mb-4 mt-4">
      <div class="card">
         <div class="card-header bg-primary text-white d-flex justify-content-between">
            <span>Nurse / Staff Details</span> <span>   </span>
         </div>
         <div class="card-body">
            <table class="table table-hover" >
               <thead class="blue lighten-4 text-center">
                  <tr>
                     <th>Roll</th>
                     <th>Name</th>
                     <th>Username</th>
                     <th>Is Staff</th>
                     <th>Status</th>
                     <th>Email</th>
                     <th>Delete</th>
                  </tr>
               </thead>
               <tbody class="text-center" >
                  {% for item in data %}              
                  <tr>
                     <th>{{ forloop.counter }}</th>
                     {% if item.is_superuser %}
                        <th>ADMIN</th>
                     {% else %}
                        <th >{{ item.first_name|capfirst }} {{ item.last_name }}</th>
                     {% endif %}
                     <th >{{ item.username }}</th>
                     <th >{% if item.is_staff %} <span class="text-danger">Yes</span> {% else %} No {% endif %}</th>
                     <th >{% if item.is_superuser %} Admin {% else %} {% if item.is_staff %} Nurse / Staff {% else %}Blogger {% endif %}{% endif %}</th>
                     <th >{{ item.email }}</th>
                     <td>
                        {% if item.is_superuser %} {% else %}
                        <a class="red-text" href="{% url 'delete_nurse' item.id %}"><strong><i class="fas fa-trash-alt"></i></strong></a>
                        {% endif %}
                     </td>
                  </tr>
                  {% endfor %}
               </tbody>
            </table>
         </div>
      </div>
   </div>
   {% endif %}
</main>
{% endblock %}