HomeApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView, name='home'),
    path('about/', views.AboutView, name='about'),
    path('services/', views.ServicesView, name='services'),
    path('gallery/', views.GalleryView, name='gallery'),
    path('shop/', views.ShopView, name='shop'),
    path('shop/<int:id>', views.ShopDetailView, name='shop_detail'),
    
    path('contact/', views.ContactView, name='contact'),
    path('appointment/', views.AppointmentView, name='appointment'),

    path('migraine/', views.MigraineView, name='migraine'),
    
    path('musculoskeletal/', views.MusculoskeletalView, name='musculoskeletal'),
    path('musculoskeletal/elbow', views.ElbowView, name='elbow'),
    path('musculoskeletal/hip', views.HipView, name='hip'),
    path('musculoskeletal/ankle', views.AnkleView, name='ankle'),
    path('musculoskeletal/shoulder', views.ShoulderView, name='shoulder'),
    path('musculoskeletal/wrist', views.WristView, name='wrist'),
    path('musculoskeletal/knee_joint', views.KneeJointView, name='knee_joint'),
    path('musculoskeletal/head_neck', views.HeadNeckView, name='head_neck'),
    path('musculoskeletal/lumbar_spine', views.LumbarSpineView, name='lumbar_spine'),

    path('neurology/', views.NeurologyView, name='neurology'),
    path('neurology/neurology_note', views.NeurologyNoteView, name='neurology_note'),
    
    path('pediatrics/', views.PediatricsView, name='pediatrics'),
    path('paediatric/paediatric_note', views.PaediatricNoteView, name='paediatric_note'),
    path('paediatric/monthly_baby_milestone', views.MonthlyBabyMilestoneView, name='monthly_baby_milestone'),

    path('success/', views.SuccessView, name='success'),
    path('error/', views.ErrorView, name='error'),
    path('search_products/', views.SearchProductsView, name="search_products"),
]

MyProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HomeApp.urls')),
    path('administration/', include('AdministrationApp.urls')),
    path('blog/', include('TheBlog.urls')),

    path('login/', include('django.contrib.auth.urls')),
    path('login/', include('LoginApp.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

TheBlog/urls.py
from django.contrib import admin
from django.urls import path
from TheBlog.views import BlogHomeView, ArticleView, CategoryView
from TheBlog.views import AddPostView, AddCommentView, AddCategoryView
from TheBlog.views import EditPostView, DeletePostView, SearchPageView

#  ================== LOGIN Urls.py =========================

# from django import views
# from .views import UserRegisterView,  PasswordsChangeView
# from django.contrib.auth import views as auth_views
# from . import views

urlpatterns = [
    path('', BlogHomeView.as_view(), name="blog_home"),
    path('article/<int:pk>', ArticleView.as_view(), name="article"),
    path('category/<str:cats>/', CategoryView, name="category"),

    path('add_post/', AddPostView.as_view(), name="add_post"),
    path('add_category/', AddCategoryView.as_view(), name="add_category"),
    path('article/<int:pk>/comment/', AddCommentView.as_view(), name="add_comment"),

    path('article/edit/<int:pk>', EditPostView.as_view(), name="edit_post"),
    path('article/<int:pk>/remove', DeletePostView.as_view(), name="delete_post"),

    path('search_page/', SearchPageView, name="search_page"),


]

TheBlog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, date
from ckeditor.fields import RichTextField

# ========= Post ==========================================

class Post(models.Model):
   title = models.CharField(max_length=255)
   header_image = models.ImageField(blank=True, null=True, upload_to="images/")
   title_tag = models.CharField(max_length=255, default="Ram's Rehab")
   author = models.ForeignKey(User,on_delete=models.CASCADE)
   body = RichTextField(blank=True, null=True)
   post_date = models.DateField(auto_now_add=True)
   category = models.CharField(max_length=255, default='others')
   snippet = models.CharField(max_length=255)
   likes = models.ManyToManyField(User, related_name='blog_posts')
   
   def total_likes(self):
      return self.likes.count()
   
   def __str__(self):
      return self.title + ' | ' + str(self.author)

   def get_absolute_url(self):
      return reverse('blog_home')


# ====== Category ======================================

class Category(models.Model):
   name = models.CharField(max_length=255)
   
   def __str__(self):
      return self.name
   
   def get_absolute_url(self):
      return reverse('blog_home')

# ====== Comment ====================================

class Comment(models.Model):
   post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
   name = models.CharField(max_length=255)
   body = models.TextField()
   date_added = models.DateTimeField(auto_now_add=True)
   
   def  __str__(self):
      return '%s - %s' % (self.post.title, self.name)

TheBlog/forms.py
from django import forms
from django.db import models
from django.forms import widgets
from TheBlog.models import Comment, Post, Category

choices = Category.objects.all().values_list('name','name')

choice_list = []
for item in choices:
   choice_list.append(item)


class PostForm(forms.ModelForm):
   class Meta:
      model = Post
      fields = ('title', 'title_tag', 'author', 'category', 'body','snippet', 'header_image')
      
      widgets = {
         'title': forms.TextInput(attrs={'class':'form-control','placeholder':'Blog Title'}),
         'title_tag': forms.TextInput(attrs={'class':'form-control','placeholder':'Blog Title Tag'}),
         'author': forms.TextInput(attrs={'class':'form-control','value':'', 'id':'dev','type':'hidden'}),
         # 'author': forms.Select(attrs={'class':'form-control'}),
         'category': forms.Select(choices=choice_list, attrs={'class':'form-control'}),
         'body': forms.Textarea(attrs={'class':'form-control','placeholder':'Blog content type here...'}),
         'snippet': forms.Textarea(attrs={'class':'form-control','placeholder':'Blog Snippet'}),
      }


class CategoryForm(forms.ModelForm):
   class Meta:
      model = Category
      fields = ('name',)
      
      widgets = {
         'name': forms.TextInput(attrs={'class':'form-control'}),
      }


class CommentForm(forms.ModelForm):
   class Meta:
      model = Comment
      fields = ('name', 'body')
      
      widgets = {
         'name': forms.TextInput(attrs={'class':'form-control'}),
         'body': forms.Textarea(attrs={'class':'form-control'}),
      }


class EditForm(forms.ModelForm):
   class Meta:
      model = Post
      fields = ('title', 'title_tag', 'body', 'snippet','header_image')
      
      widgets = {
         'title': forms.TextInput(attrs={'class':'form-control'}),
         'title_tag': forms.TextInput(attrs={'class':'form-control'}),
         'body': forms.Textarea(attrs={'class':'form-control'}),
         'snippet': forms.Textarea(attrs={'class':'form-control'}),
      }

TheBlog/views.py
from django.urls.base import reverse
from django.urls import reverse_lazy,reverse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, request

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from TheBlog.models import Category, Post, Comment
from TheBlog.forms import PostForm, CommentForm, EditForm, CategoryForm


class BlogHomeView(ListView):
   model = Post
   template_name = 'blogs/blog_home.html'
   cats = Category.objects.all()
   ordering = ['-post_date']
   
   def get_context_data(self, *args, **kwargs):
      cat_menu = Category.objects.all()
      context = super(BlogHomeView, self).get_context_data(*args, **kwargs)
      context["cat_menu"] = cat_menu
      return context
   

class ArticleView(DetailView):
   model = Post
   template_name = 'blogs/article.html'
   
   def get_context_data(self, *args, **kwargs):
      cat_menu = Category.objects.all()
      context = super(ArticleView, self).get_context_data(*args, **kwargs)
      
      stuff = get_object_or_404(Post, id=self.kwargs['pk'])
      total_likes = stuff.total_likes()
      
      liked = False
      if stuff.likes.filter(id=self.request.user.id).exists():
         liked = True
         
      context["cat_menu"] = cat_menu
      context["total_likes"] = total_likes
      context["liked"] = liked
      return context


def CategoryView(request, cats):
   category_posts = Post.objects.filter(category=cats.replace('-',' '))
   return render(request, 'blogs/blog_by_category.html', {'cats':cats.title().replace('-',' '), 'category_posts':category_posts})



class AddPostView(CreateView):
   model = Post
   form_class = PostForm
   template_name = 'blogs/blog_add_post.html'
   success_url = reverse_lazy('blog_home')


class AddCategoryView(CreateView):
   model = Category
   form_class = CategoryForm
   template_name = 'blogs/blog_add_category.html'
   # fields = '__all__'
   
   def get_context_data(self, *args, **kwargs):
      cat_menu_list = Category.objects.all()
      context = super(AddCategoryView, self).get_context_data(*args, **kwargs)
      context["cat_menu_list"] = cat_menu_list
      return context
   success_url = reverse_lazy('add_category')


class AddCommentView(CreateView):
   model = Comment
   form_class = CommentForm
   template_name = 'blogs/blog_add_comment.html'
   
   def form_valid(self, form):
      form.instance.post_id = self.kwargs['pk']
      return super().form_valid(form)
   success_url = reverse_lazy('blog_home')


class EditPostView(UpdateView):
   model = Post
   form_class = EditForm
   template_name = 'blogs/blog_edit_post.html'
   success_url = reverse_lazy('blog_home')

   
class DeletePostView(DeleteView):
   model = Post
   template_name = 'blogs/blog_delete_post.html'
   success_url = reverse_lazy('blog_home')


def SearchPageView(request):
   if request.method == 'POST':
      searched = request.POST['searched']
      search_post = Post.objects.filter(title__icontains=searched)
      search_category = Post.objects.filter(category__icontains=searched)
      
      return render(request, 'blogs/search_page.html', {
         'searched':searched, 
         'search_post':search_post, 
         'search_category':search_category
         })
   else:    
      return render(request, 'blogs/search_page.html', {})   

TheBlog/templates/blogs/article.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ post.title_tag }} {% endblock %}
{% block content %}
<main id="main">
   <style>
      .about_bg{
      background: url("{% static 'home/img/bg/bg_1.jpg' %}");
      background-repeat: no-repeat;
      background-size: cover;
      }
   </style>
   <section class="breadcrumbs">
      <div class="container">
         <div class="d-flex justify-content-between align-items-center">
            <h2>Blogs</h2>
            <ol>
               <li><a href="{% url 'home' %}">Home</a></li>
               <li>Blogs</li>
            </ol>
         </div>
      </div>
   </section>
   <section class="inner-page about_bg">
      <div class="container ">
         
         {% include 'blogs/searchbox.html' %}
         
         <div class="d-flex justify-content-between  mx-auto">
            <div>
               <p>Auther : {{ post.author.first_name }} {{ post.author.last_name }} </p>
               <p>Date : {{ post.post_date | date:'d-m-Y' }}</p>
            </div>
            <div>
               <p>Category : <a href="{% url 'category' post.category|slugify %}">{{ post.category | capfirst  }}</a></p>
               {% if user.is_authenticated %}
               {% if user.id == post.author.id %}
               <a class="btn btn-sm btn-warning mx-1" href="{% url 'edit_post' post.pk %}">Edit Post</a></small>
               <a class="btn btn-sm btn-danger mx-1" href="{% url 'delete_post' post.pk %}">Delete Post</a></small><br/>
               {% endif %}
               {% endif %}
            </div>
         </div>
         <div class="section-title">
            <h2>{{post.title}}</h2>
            {% if post.header_image %}
               <img style="display: block; margin-left: auto; margin-right: auto; max-width: 80%;" 
               src="{{ post.header_image.url}}" alt="image of {{ post.title }}">
            {% endif %}
         </div>
         <div class="container">
            
            <br/>
            <br/>
            <p class="text-justify">{{ post.body|safe }}</p>
         </div>
      </div>
   </section>
   <section class="breadcrumbs">
      <div class="container">
         <div class="d-flex justify-content-between align-items-center mb-3">
            <h2><b>Comments</b></h2>
            <ol>
               <li><a class="btn btn-info btn-sm" href="{% url 'add_comment' post.pk %}">Add Comments</a></li>
            </ol>
            <div>
               {% if not post.comments.all %}
                  <p>No Comments Yet</p> 
               {% else %}
                  <button type="button" class="btn btn-sm btn-success">
                     <span class="badge badge-light">{{ post.comments.all.count }}</span> Comments
                   </button>
               {% endif %}
            </div>

         </div>
         <div class="d-flex flex-column mr-auto align-items-center">
            {% if post.comments.all %}
               {% for comment in post.comments.all %}
               <div class="col-md-8">
                  <div class="card mb-3">
                     <div class="card-header text-white bg-info py-1">
                       {{ comment.name | capfirst }} 
                     </div>
                     <div class="card-body py-3">
                       <blockquote class="mb-0">
                         <p>{{ comment.body }}</p>
                         <footer class="blockquote-footer">
                            <cite title="Source Title d-flex">{{ comment.date_added | date:'d-m-Y  [ H:i A ]' }} </cite></footer>
                       </blockquote>
                     </div>
                   </div>
               </div>
                  {% endfor %}
               {% endif %}
        
                  
         </div>
      </div>
   </section>

</main>
{% endblock content %}

TheBlog/templates/blogs/blog_add_category.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Create New Blog Post {% endblock %}
{% block content %}
<main id="main">
   <style>
      .appointment-bg{
      background: url("{% static 'assets/img/logo/logo_light.png' %}");
      background-repeat: no-repeat;
      background-size: cover;
      }
   </style>
   <section class="breadcrumbs">
      <div class="container">
         <div class="d-flex justify-content-between align-items-center">
            <h2>Add Blog Post</h2>
            <ol>
               <li><a href="{% url 'home' %}">Home</a></li>
               <li>Add Blog Post</li>
            </ol>
         </div>
      </div>
   </section>
   <section id="Appointment" class="contact ">
      <div class="container">
         <div class="section-title">
            {% if user.is_authenticated %}
            <h2>Add Categories</h2>
            <p></p>
            {% endif %}
         </div>
      </div>
      <style>
         #postform p{
         display: flex;
         }
         #postform label{
         margin-right: 10px;
         padding:5px 10px 0 10px;
         width: 200px;
         max-width: 200px;
         vertical-align: middle;
         }
         #postform input select{
         margin: 10px;
         padding: 10px;
         width: 400px;
         max-width: 500px;
         }
         #postform .django-ckeditor-widget{
         margin-bottom: 40px;
         }
         #postform #id_snippet{
         margin-bottom: 40px;
         }
         #postform #id_header_image {
         margin-bottom: 40px;
         }
         .submit_button{
         background: #1977cc;
         border: 0;
         padding: 10px 35px;
         color: #fff;
         transition: 0.4s;
         border-radius: 50px;
         cursor: pointer;
         -webkit-appearance: button;
         text-transform: none;
         overflow: visible;
         margin: 0;
         font-family: inherit;
         font-size: inherit;
         line-height: inherit;
         text-align: center !important;
         font-weight: 400;
         }
      </style>
      <div class="container">
         <div class="row mt-3 text-center mx-auto">
            <div class="col-lg-6 mt-5 mt-lg-0">
               {% if user.is_authenticated %}
               <form id="postform"  method="POST" >
                  {% csrf_token %}
                  <div class="col-md-9">
                     {{ form.as_p }}
                     <button type="submit" class="submit_button mt-3">Add Category</button>
                  </div>
               </form>
               {% else %}
               <div class="section-title">
                  <h2>You Can't allow here..</h2>
                  <p>You Can't Add Categories..Please login</p>
                  <a href="{% url 'login' %}">
                  <button class="submit_button mt-4 mr-2"><i class="icofont-login"></i> Login</button>
                  </a>
                  <a href="{% url 'home' %}">
                  <button class="submit_button mt-3"><i class="icofont-home"></i> Home</button>
                  </a>
               </div>
               {% endif %}
            </div>
            <div class="col-lg-6 mt-5 mt-lg-0">
               <table class="table">
                  <thead>
                     <tr>
                        <th scope="col">Roll</th>
                        <th scope="col">Categories</th>
                     </tr>
                  </thead>
                  <tbody>
                     {% for item in cat_menu_list %}
                     <tr>
                        <th>{{ forloop.counter }}</th>
                        <td><a href="{% url 'category' item|slugify %}">{{ item | capfirst }}</a></td>
                     </tr>
                     {% endfor %}
                  </tbody>
               </table>
            </div>
         </div>
      </div>
   </section>
</main>
{% endblock content %}

TheBlog/templates/blogs/blog_add_comment.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Comments {% endblock %}
{% block content %}
<main id="main">
   <style>
      .appointment-bg{
      background: url("{% static 'assets/img/logo/logo_light.png' %}");
      background-repeat: no-repeat;
      background-size: cover;
      }
   </style>
   <section class="breadcrumbs">
      <div class="container">
         <div class="d-flex justify-content-between align-items-center">
            <h2>Add Comments</h2>
            <ol>
               <li><a href="{% url 'home' %}">Home</a></li>
               <li>Add Comments</li>
            </ol>
         </div>
      </div>
   </section>
   <section id="Appointment" class="contact ">
      <div class="container">
         <div class="section-title">
            <h2>Add Comments</h2>
            <p></p>
         </div>
      </div>
      <style>
         #postform p{
         display: flex;
         }
         #postform label{
         margin-right: 10px;
         padding:5px 10px 0 10px;
         width: 200px;
         max-width: 200px;
         vertical-align: middle;
         }
         #postform input select{
         margin: 10px;
         padding: 10px;
         width: 400px;
         max-width: 500px;
         }
         #postform .django-ckeditor-widget{
         margin-bottom: 40px;
         }
         #postform #id_snippet{
         margin-bottom: 40px;
         }
         #postform #id_header_image {
         margin-bottom: 40px;
         }
         .submit_button{
            background: #1977cc;
            border: 0;
            padding: 10px 35px;
            color: #fff;
            transition: 0.4s;
            border-radius: 50px;
            cursor: pointer;
            -webkit-appearance: button;
            text-transform: none;
            overflow: visible;
            margin: 0;
            font-family: inherit;
            font-size: inherit;
            line-height: inherit;
            text-align: center !important;
            font-weight: 400;
         }
      </style>
      <div class="container ">
         <div class="row mt-3">
            <div class="col-lg-12 mt-5 mt-lg-0">
               {% if user.is_authenticated %}
               <form id="postform"  method="POST">
                  {% csrf_token %}
                  <div class="col-md-8 text-center mx-auto">
                     {{ form.as_p }}
                     <button type="submit" class="submit_button">Submit Comment</button>
                  </div>
               </form>
               {% endif %}
            </div>
            
            
         </div>
      </div>
   </section>
</main>
{% endblock content %}

TheBlog/templates/blogs/blog_add_post.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Create New Blog Post {% endblock %}
{% block content %}
<main id="main">
   <style>
      .appointment-bg{
      background: url("{% static 'assets/img/logo/logo_light.png' %}");
      background-repeat: no-repeat;
      background-size: cover;
      }
   </style>
   <section class="breadcrumbs">
      <div class="container">
         <div class="d-flex justify-content-between align-items-center">
            <h2>Add Blog Post</h2>
            <ol>
               <li><a href="{% url 'home' %}">Home</a></li>
               <li>Add Blog Post</li>
            </ol>
         </div>
      </div>
   </section>
   <section id="Appointment" class="contact ">
      <div class="container">
         <div class="section-title">
            {% if user.is_authenticated %}
            <h2>Add Blog Post</h2>
            <p class="text-danger">* Header Image Size : 1024 X 692 Pixels</p>
            {% else %}
            <h2>You Can't allow here..</h2>
            <p>You Can't Add Post..Please login</p>
            
            <a href="{% url 'login' %}">
               <button class="submit_button mt-4 mr-2"><i class="icofont-login"></i> Login</button>
            </a>
            <a href="{% url 'home' %}">
               <button class="submit_button mt-3"><i class="icofont-home"></i> Home</button>
            </a>
            {% endif %}
         </div>
      </div>
      <style>
         #postform p{
         display: flex;
         }
         #postform label{
         margin-right: 10px;
         padding:5px 10px 0 10px;
         width: 200px;
         max-width: 200px;
         vertical-align: middle;
         }
         #postform input select{
         margin: 10px;
         padding: 10px;
         width: 400px;
         max-width: 500px;
         }
         #postform .django-ckeditor-widget{
         margin-bottom: 40px;
         }
         #postform #id_snippet{
         margin-bottom: 40px;
         }
         #postform #id_header_image {
         margin-bottom: 40px;
         }
         .submit_button{
            background: #1977cc;
            border: 0;
            padding: 10px 35px;
            color: #fff;
            transition: 0.4s;
            border-radius: 50px;
            cursor: pointer;
            -webkit-appearance: button;
            text-transform: none;
            overflow: visible;
            margin: 0;
            font-family: inherit;
            font-size: inherit;
            line-height: inherit;
            text-align: center !important;
            font-weight: 400;
         }
      </style>
      <div class="container ">
         <div class="row mt-3">
            <div class="col-lg-12 mt-5 mt-lg-0">
               {% if user.is_authenticated %}
               <form id="postform"  method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ form.media }}
                  <div class="col-md-8 text-center mx-auto">
                     {{ form.as_p }}
                     <button type="submit" class="submit_button">Submit Blog Post</button>
                  </div>
               </form>
               <script>
                  var name = "{{ user.id }}";
                  document.getElementById("dev").value = name;
               </script>
               {% else %}
               
               {% endif %}
              
            </div>
            
            
         </div>
      </div>
   </section>
</main>
{% endblock content %}

TheBlog/templates/blogs/blog_edit_post.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Edit Blog Post {% endblock %}
{% block content %}
<main id="main">
   <style>
      .appointment-bg{
      background: url("{% static 'assets/img/logo/logo_light.png' %}");
      background-repeat: no-repeat;
      background-size: cover;
      }
   </style>
   <style>
      #postform p{
      display: flex;
      }
      #postform label{
      margin-right: 10px;
      padding:5px 10px 0 10px;
      width: 200px;
      max-width: 200px;
      vertical-align: middle;
      }
      #postform input select{
      margin: 10px;
      padding: 10px;
      width: 400px;
      max-width: 500px;
      }
      #postform .django-ckeditor-widget{
      margin-bottom: 40px;
      }
      #postform #id_snippet{
      margin-bottom: 40px;
      }
      #postform #id_header_image {
      margin-bottom: 40px;
      }
      .submit_button{
      background: #1977cc;
      border: 0;
      padding: 10px 35px;
      color: #fff;
      transition: 0.4s;
      border-radius: 50px;
      cursor: pointer;
      -webkit-appearance: button;
      text-transform: none;
      overflow: visible;
      margin: 0;
      font-family: inherit;
      font-size: inherit;
      line-height: inherit;
      text-align: center !important;
      font-weight: 400;
      }
   </style>
   <section class="breadcrumbs">
      <div class="container">
         <div class="d-flex justify-content-between align-items-center">
            <h2>Edit Blog Post</h2>
            <ol>
               <li><a href="{% url 'home' %}">Home</a></li>
               <li>Blogs</li>
            </ol>
         </div>
      </div>
   </section>
   <section id="Appointment" class="contact ">
      <div class="container">
         {% if user.id == post.author.id %}
         <div class="section-title">
            <div style="font-size: xx-large; margin-bottom: 10px;">
               <i class="icofont-edit-alt"></i>
            </div>
            <h2>Edit Blog Post</h2>
         </div>
         {% else %}
         <div class="section-title">
            <div style="font-size: xxx-large;color: #f00808; margin-bottom: 10px;">
               <i class="icofont-exclamation-tringle"></i>
            </div>
            <h2 class="text-danger">You are not allowed here..!!</h2>
            <p>Only the Auther can Edit the post.. Please login</p>
            <p></p>
            <a href="#">
               <button class="submit_button mt-3"><i class="icofont-login"></i> Login</button>
            </a>
            <a href="{% url 'home' %}">
               <button class="submit_button mt-3"><i class="icofont-home"></i> Home</button>
            </a>
         </div>
         {% endif %}
         <div class="container ">
            <div class="row mt-3">
               <div class="col-lg-12 mt-5 mt-lg-0">
                  {% if user.is_authenticated %}
                  {% if user.id == post.author.id %}
                  <form id="postform"  method="POST" enctype="multipart/form-data">
                     {% csrf_token %}
                     {{ form.media }}
                     <div class="col-md-8 text-center mx-auto">
                        {{ form.as_p }}
                        <button type="submit" class="submit_button">Update Post</button>
                     </div>
                  </form>
                  {% else %}
                  <div class="section-title">
                     <div style="font-size: xxx-large;color: #f00808; margin-bottom: 10px;">
                        <i class="icofont-exclamation-tringle"></i>
                     </div>
                     <h2 class="text-danger">You are not allowed here..!!</h2>
                     <p>Only the Auther can Edit the post.. Please login</p>
                     <p></p>
                     <a href="#">
                        <button class="submit_button mt-3"><i class="icofont-login"></i> Login</button>
                     </a>
                     <a href="{% url 'home' %}">
                        <button class="submit_button mt-3"><i class="icofont-home"></i> Home</button>
                     </a>
                  </div>
                  {% endif %}
                  {% endif %}
               </div>
            </div>
         </div>
      </div>
   </section>
</main>
{% endblock content %}

TheBlog/templates/blogs/searchbox.html
<nav class="navbar navbar-light justify-content-center">
   <form action="{% url 'search_page' %}" method="POST" class="form-inline">
      {% csrf_token %}
      <div class="input-group mb-3" >
         <input type="search" name="searched"  class="form-control outline-info" placeholder="Search blogs" aria-describedby="basic-addon1">
         <div class="input-group-prepend" >
            <button  type="submit" class="btn btn-outline-info" id="basic-addon1"><i class="icofont-search"></i></button>
         </div>
      </div>
   </form>
 </nav>